name: test
on: [push]

jobs:
  test-freebsd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test in FreeBSD
        uses: vmactions/freebsd-vm@v1
        with:
          arch: aarch64
          usesh: true
          prepare: |
            pkg install -y -f curl node libnghttp2 npm yarn
            echo "~~~~ node -v ~~~~"
            node -v
            echo "~~~~ yarn --version ~~~~"
            yarn --version
          run: |
            pwd
            ls -lah
            whoami
            env
            freebsd-version
            sysctl hw.model
            sysctl hw.ncpu
            sysctl hw.physmem
            sysctl hw.usermem
            make freebsd-arm64
            ls -AFGhl ./npm/watcher/parcel-watcher*.tgz
